### ISSUE TITLE
Exposé - Bahnbuddy

### ISSUE THREAD

**Issue by KerstenRon** [scarcloud/EISSS16VilentsKersten#1]
Am besten erwähnt man noch das Problem der Grauzone dass, das Mitnehmen der Personen noch vor Fahrtantritt vereinbart sein muss und die App als Beweis für die vorangegangene Vereinbarung dient. ;)

Außerdem bin ich der Meinung das der mögliche Lösungsansatz einer App "BahnBuddy" nicht in das Exposé gehört.

Sonst is das Exposé echt gut

**Comment by scarcloud** [comment]
Naja, als Beweis eher weniger, sondern als Organisationstool halt. Dass Du die Leute mitnimmst, musst Du ja nicht wirklich beweisen, sondern einfach vorher ausmachen, und nicht wenn der Kontroller vor dir steht.
